import type { Metadata } from "next";
import Image from "next/image";
import { PageFooter, PageFrame } from "../../components/editorial/PageFrame";
import styles from "../phase-two.module.css";
import { createPageMetadata } from "../../lib/seo";
import { absoluteSiteUrl, siteUrl } from "../../lib/seo";
import { socialLinks } from "../../content/site";
export const metadata: Metadata = createPageMetadata({ title: "About", description: "About Chuka Dele-Oyeleru, a Strategy & Operations practitioner based in Manchester, UK.", path: "/about", image: "/images/social/about.jpg", imageAlt: "Portrait of Chuka Dele-Oyeleru" });
const principles = [
  ["Start with the real constraint", "The first brief is rarely the whole problem. I read the environment, incentives and information before prescribing a system."],
  ["Make ownership visible", "A plan becomes operable when decisions, responsibilities and hand-offs are clear."],
  ["Use the discipline the problem needs", "Strategy, operations, product, people, data and growth are inputs, not identity labels."],
  ["Build for use", "The work has to survive contact with the team that will run it."],
  ["Improve from evidence", "Feedback belongs inside the system, not in a retrospective added after delivery."],
];
export default function AboutPage() { return <PageFrame tone="blue">
  {siteUrl ? <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "ProfilePage", "@id": `${absoluteSiteUrl("/about")}#profile`, url: absoluteSiteUrl("/about"), name: "About Chuka Dele-Oyeleru", mainEntity: { "@type": "Person", "@id": `${absoluteSiteUrl("/")}#chuka`, name: "Chuka Dele-Oyeleru", jobTitle: "Strategy & Operations", url: absoluteSiteUrl("/"), sameAs: [socialLinks.linkedin] } }) }} /> : null}
  <header className={`${styles.hero} ${styles.aboutHero}`}><p className={styles.heroIndex}>05 / ABOUT</p><div className={styles.heroCopy}><p className={styles.marker}>MANCHESTER, UK</p><h1>The breadth comes from the <em>work.</em></h1><p>I work across Strategy &amp; Operations. The common thread is making ambiguous, cross-functional work usable.</p></div><figure><Image src="/images/portraits/chuka-about.webp" width="1400" height="1751" priority sizes="(max-width: 899px) 100vw, 38vw" alt="Chuka Dele-Oyeleru seated in a black T-shirt against a dark studio backdrop."/></figure></header>
  <section className={styles.aboutIntro}><p className={styles.marker}>How the toolkit grew</p><div><h2>The problems became broader. So did the work.</h2><p>I trained in Quantity Surveying, moved into people and operating work, worked inside a scaling insurtech, then into venture, product and service building. I now study for an MBA at Alliance Manchester while increasingly using technology, AI and data to improve execution. The breadth is a response to the problems, not a collection of identity labels.</p><nav aria-label="About routes"><a href="/work">Explore selected work →</a><a href="/resume">Read the professional record →</a><a href="/speaking">Explore speaking topics →</a></nav></div></section>
  <section className={styles.aboutPath} aria-labelledby="path-title"><p className={styles.marker}>A connected path</p><div><h2 id="path-title">From the built environment to operating environments.</h2><ol><li><span>2016–2021</span><strong>Quantity Surveying</strong><p>Studied how cost, materials, decisions and delivery connect inside complex projects.</p></li><li><span>2022–2024</span><strong>ETAP</strong><p>Moved from executive-support work into operations leadership inside a growing insurtech.</p></li><li><span>2024–Present</span><strong>Venture building</strong><p>Works across Rvysion and The Bredge on commercial, operating, product and service systems.</p></li><li><span>2025–2027</span><strong>MBA</strong><p>Studies at Alliance Manchester Business School while continuing to build and operate.</p></li></ol></div></section>
  <section className={styles.aboutBody}><div><p className={styles.aboutStatement}>A way of seeing the whole operating problem.</p><p className={styles.aboutPersonal}>Away from the work, I make time for running, tennis, hiking, kayaking, reading and the communities I learn with.</p></div><ol className={styles.principles}>{principles.map(([title,body])=><li key={title}><div><strong>{title}</strong><p>{body}</p></div></li>)}</ol></section><PageFooter />
</PageFrame>; }
